Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,25 +1,27 @@
 #!/data/data/com.termux/files/usr/bin/bash
 # COLORS
-cd $HOME
-os="$1"
-XorCLi="$2"
-case "$XorCLi" in
-  g)
-    extra_args="-nographic"
-    ;;
-  v)
-    extra_args="-vnc :1"
-    ;;
-  *)
-    echo "Goblok ga ada"
-    ;;
-esac
+W="\e[0m"
+R="\e[31m"
+G="\e[32m"
+Y="\e[33m"
+B="\e[34m"
+os="alpine"
 
-case "$os" in
-  *)
-    qemu-system-x86_64 -machine q35 -m "$(free --mega | grep 'Mem' | awk '{print $2}')" -smp "$(nproc)" -cpu qemu64 -vga virtio -full-screen -usb -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 $extra_args "$os"
-    ;;
-  *)
-    echo "Sistem operasi yang diberikan tidak didukung."
-    ;;
-esac
+[[ $# -eq 0 ]] && { echo -en "\e[33mUsage:\e[0m $0 <operative system name> x11[for a grafical enviroment]";exit;}
+[[ $2 == 'x11' ]] 2>/dev/null || { XorCLi="-nographic";}
+[[ -d ${HOME}/$os ]] && {
+  cd ${HOME}/$os
+  case "$os" in
+    alpine)
+      qemu-system-x86_64 -machine q35 -m $(free --mega|grep "Mem"|awk '{print $2}') -smp \
+        cpus=$(nproc) -cpu qemu64 -vga virtio -full-screen -usb \
+        -drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
+        -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 \
+        $XorCLi $os.img
+      ;;
+  esac
+} || {
+  echo -en $R"E:$W $(basename $0) PATH missing ...$Y Aborting.$W"
+  exit 1
+}
+####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
